### ISSUE TITLE
1.13.2 support.

### ISSUE THREAD

**Issue by theblobinc** [Jonodonozym/JonosBukkitUtils#1]
we have been trying to compile this for 1.13.2 and have had fairly bad luck getting it to actually run, is there a chance you could look into an update if you have the time?

alot of the gc plugins depend upon this.

**Comment by Tungsten-W-74** [comment]
Does the plugin itself fail, or just the other plugins which depend on it?
If it's the utils plugins, send me the error log and I'll have a look. If
it's the other plugins, I'll need a list of those to fix them individually.

Alternatively, you can use an older version of the utils.

I've been making a lot of changes to the utils API, which is why the latest
version is not compatible with older plugins.

**Comment by theblobinc** [comment]
the older version doesent run at all, its just all errors.

if you look at the fork I have made, I updated its vaultAPI repo to the backup because the vaultAPI repo is down.

I have likewise updated its dependencies to vault 1.7, worldedit 7.0.0-snapshot, and ofc spigot-api-1.13.2-r0.1.
https://github.com/theblobinc/JonosBukkitUtils/commit/d2900a68715737fb6c0ed72aa32153192b639d36

although it had errors in eclipse, upon being compiled with maven(via command line) it initiates on 1.13.2 without error by its self, but once run with gcboosters(which I also tried to update in a similar manner) I get a lengthy error detailed here:
https://pastebin.com/Y4tSb9NE

**Comment by theblobinc** [comment]
this is a server log with just my updated version of jbu running without any of its dependent plugins, all seems fine.
https://pastebin.com/yRC2wKrT

all of this testing is being done on my survival 1.13.2 prototype server on gc on the miniontest server.
(which is at a point in its development that now requires the gc plugins to go further)

**Comment by Tungsten-W-74** [comment]
Seems like gcBoosters is loading before JBU for some reason, causing it to mess up. I've [updated the gcBooster plugin](https://github.com/Jonodonozym/gcBoosters/commit/3ddfe5aa39dee025ed1ce38a0e6714ea125f469a) to resolve this issue.

I also [made a change](https://github.com/Jonodonozym/JonosBukkitUtils/commit/e8842639ffe2e8736c193b1786ac0f8883eff7a3) to JBU to ensure this issue doesn't cause JBU to crash.

Try those changes on your end and see if that resolved the issue. If not, contact me on discord (Jono
#7396) to organise a time where were both online so I can work on the issue live.

**Comment by theblobinc** [comment]
kk will work on that tonight some more maybe, I gota do some other work on my dev server anyways.
